variables:
  EXTERNAL_NET: shared_ext

Deploy:
  stage: deploy
  tags:
    - ontime-staging
  rules:
    - if: $CI_COMMIT_BRANCH == "develop"
    - if: $CI_COMMIT_BRANCH == "main"
  script:
    - docker network create $EXTERNAL_NET || true
    - docker compose down
    - docker compose up -d --build
